version: '3'

services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_DATABASE: dartsapi
      MYSQL_ROOT_PASSWORD: example
      MYSQL_PASSWORD: root
  back:
    image: darts-api:latest
    build: .
    container_name: darts-api-srv
    ports:
      - 8080:8080
    depends_on:
      - mariadb